import type { LucideIcon } from "lucide-react";
import {
  Layout,
  GitPullRequest,
  PanelsTopLeft,
  PenLine,
  GraduationCap,
  Video,
  Terminal,
  ShieldCheck,
} from "lucide-react";

/**
 * A static, reusable starter prompt for the Atlas "Builder" surface.
 * These do NOT add any AI plumbing — they only produce a prompt string
 * that Atlas injects into the composer via its existing onPick callback.
 */
export type BuilderPromptCard = {
  id: string;
  title: string;
  description: string;
  icon: LucideIcon;
  prompt: string;
};

export const BUILDER_PROMPT_CARDS: BuilderPromptCard[] = [
  {
    id: "website-brief",
    title: "Build a website brief",
    description: "Turn a rough idea into a structured website brief with goals, pages, and content.",
    icon: Layout,
    prompt: [
      "Act as a senior product strategist. Help me write a complete website brief.",
      "",
      "Ask me anything you still need, then produce a brief with these sections:",
      "1. Business & audience — who this is for and the primary goal of the site.",
      "2. Success metrics — the 2–3 outcomes that define a winning site.",
      "3. Sitemap — the list of pages with a one-line purpose for each.",
      "4. Page-by-page content outline — sections, headlines, and CTAs per page.",
      "5. Tone & visual direction — voice, mood, and 3–5 reference styles.",
      "6. Technical notes — framework, integrations, forms, analytics, SEO basics.",
      "7. Open questions & assumptions.",
      "",
      "My starting idea:",
    ].join("\n"),
  },
  {
    id: "review-repo",
    title: "Review a repo",
    description: "Get a structured walkthrough and review plan for an unfamiliar codebase.",
    icon: GitPullRequest,
    prompt: [
      "Act as a staff engineer reviewing an unfamiliar repository. Produce a review plan and findings.",
      "",
      "Cover:",
      "1. Architecture overview — main modules, data flow, and entry points.",
      "2. Tech stack & conventions — languages, frameworks, patterns in use.",
      "3. Strengths — what is well done and worth keeping.",
      "4. Risks & smells — coupling, dead code, missing tests, security concerns.",
      "5. Prioritized recommendations — quick wins vs. larger refactors.",
      "6. Suggested reading order for a new contributor.",
      "",
      "Be concrete and cite file paths or modules. Repo or code to review:",
    ].join("\n"),
  },
  {
    id: "landing-page",
    title: "Create a landing page prompt",
    description: "Generate a high-converting landing page spec ready to hand to a builder or designer.",
    icon: PanelsTopLeft,
    prompt: [
      "Act as a conversion copywriter and landing page designer. Write a complete landing page spec.",
      "",
      "Deliver, in order:",
      "1. Hero — headline, subhead, primary CTA, and supporting visual direction.",
      "2. Social proof — logos, testimonials, or stats to feature.",
      "3. Problem → solution — the pain and how the offer solves it.",
      "4. Features/benefits — 3–5 blocks, each benefit-led with a short proof point.",
      "5. Objection handling — FAQ or risk-reversal section.",
      "6. Final CTA — a strong closing offer.",
      "7. SEO meta title & description.",
      "",
      "Product / offer and target audience:",
    ].join("\n"),
  },
  {
    id: "blog-post",
    title: "Create a blog prompt",
    description: "Outline and draft an SEO-aware blog post with a clear angle and structure.",
    icon: PenLine,
    prompt: [
      "Act as an expert content writer. Help me plan and draft a blog post.",
      "",
      "Provide:",
      "1. A working title plus 3 alternates.",
      "2. The target reader and the single takeaway they should leave with.",
      "3. A primary keyword and 3–5 supporting keywords.",
      "4. A section-by-section outline with H2/H3 headings.",
      "5. A full first draft in a clear, scannable voice with examples.",
      "6. A meta description (max 155 chars) and 3 suggested internal-link topics.",
      "",
      "Topic, audience, and any sources or angle I want:",
    ].join("\n"),
  },
  {
    id: "training-lesson",
    title: "Create a training lesson",
    description: "Build a teachable lesson with objectives, steps, and a knowledge check.",
    icon: GraduationCap,
    prompt: [
      "Act as an instructional designer. Build a single self-contained training lesson.",
      "",
      "Structure it as:",
      "1. Lesson title and one-sentence summary.",
      "2. Learning objectives — what the learner can do afterward.",
      "3. Prerequisites and estimated time.",
      "4. Core content — explained in plain language with at least one worked example.",
      "5. Step-by-step walkthrough or demo script.",
      "6. Common mistakes and how to avoid them.",
      "7. Knowledge check — 3–5 questions with answers.",
      "8. Recap and next steps.",
      "",
      "Topic and the audience's current skill level:",
    ].join("\n"),
  },
  {
    id: "screen-recording",
    title: "Create a screen recording action plan",
    description: "Plan a clear, well-paced screen recording with a shot list and script.",
    icon: Video,
    prompt: [
      "Act as a video producer. Help me plan a screen recording walkthrough.",
      "",
      "Produce:",
      "1. Goal & audience — what the viewer should be able to do after watching.",
      "2. Target length and tone.",
      "3. Pre-flight checklist — windows to open, demo data, resolution, notifications off.",
      "4. Shot list — each segment with the on-screen action and what to narrate.",
      "5. A spoken script aligned to the shot list.",
      "6. On-screen callouts / zoom moments to highlight.",
      "7. Outro and call to action.",
      "",
      "What I'm recording and who it's for:",
    ].join("\n"),
  },
  {
    id: "claude-code-handoff",
    title: "Create a Claude Code handoff",
    description: "Write a precise, self-contained task brief for a Claude Code coding agent.",
    icon: Terminal,
    prompt: [
      "Write a self-contained handoff brief for a Claude Code coding agent so it can implement a change with no further context.",
      "",
      "Include:",
      "1. Objective — the outcome in one or two sentences.",
      "2. Context — relevant files, modules, and how they fit together.",
      "3. Exact scope — what to change and, explicitly, what NOT to touch.",
      "4. Step-by-step plan — ordered, concrete implementation steps.",
      "5. Constraints — conventions, types, dependencies allowed, style rules.",
      "6. Acceptance criteria — how we'll know it's done and correct.",
      "7. Verification — how to test or check the result.",
      "",
      "The task I want handed off:",
    ].join("\n"),
  },
  {
    id: "codex-review",
    title: "Create a Codex review prompt",
    description: "Draft a focused code-review prompt for an automated reviewer like Codex.",
    icon: ShieldCheck,
    prompt: [
      "Write a focused code-review prompt for an automated reviewer (e.g. Codex) to run against a diff or pull request.",
      "",
      "The prompt should direct the reviewer to check:",
      "1. Correctness — logic bugs, edge cases, and off-by-one errors.",
      "2. Security — injection, auth/permission gaps, unsafe input handling, secret leaks.",
      "3. Performance — needless work, N+1 queries, and obvious bottlenecks.",
      "4. Readability & conventions — naming, structure, and project style.",
      "5. Tests — missing coverage and weak assertions.",
      "",
      "Ask the reviewer to report findings by severity with file/line references and a concrete suggested fix for each.",
      "",
      "The change or PR to review:",
    ].join("\n"),
  },
];
