import {
  Bell,
  BookOpen,
  Bot,
  Brain,
  Briefcase,
  Calendar,
  ChartLine,
  ClipboardList,
  Factory,
  FileStack,
  FolderTree,
  GraduationCap,
  ImageIcon,
  Inbox,
  LayoutDashboard,
  Mail,
  MessageCircle,
  Puzzle,
  Rocket,
  Settings,
  ShieldAlert,
  ShieldCheck,
  PlayCircle,
  Plug,
  Share2,
  Sparkles,
  Trophy,
  UserCheck,
  UserPlus,
  Users,
  Workflow,
  Wrench,
  type LucideIcon,
} from "lucide-react";

import type { NavGate } from "@/lib/permissions";

export interface NavItem {
  href: string;
  label: string;
  description?: string;
  icon: LucideIcon;
  gate?: NavGate;
  section: "core" | "mortgage" | "studios" | "team" | "owner";
}

export const NAV_ITEMS: NavItem[] = [
  {
    section: "core",
    href: "/dashboard",
    label: "Command Center",
    description: "Home, alerts, recent activity",
    icon: LayoutDashboard,
  },
  {
    section: "core",
    href: "/onboarding",
    label: "Onboarding",
    description: "Your role, integrations, and next steps",
    icon: Rocket,
  },
  {
    section: "core",
    href: "/atlas",
    label: "Atlas Chat",
    description: "Hermes-style AI assistant",
    icon: MessageCircle,
  },
  {
    section: "core",
    href: "/knowledge",
    label: "Knowledge Sources",
    description: "Collections and retrieval",
    icon: BookOpen,
  },
  {
    section: "core",
    href: "/browser-companion",
    label: "Browser Companion",
    description: "Chrome extension — capture portal context into Atlas/FLO",
    icon: Puzzle,
  },
  {
    section: "mortgage",
    href: "/loan-brain",
    label: "Loan Brain",
    description: "Read-only Drive borrower file browser",
    icon: FolderTree,
    gate: { ownerOnly: true },
  },
  {
    section: "mortgage",
    href: "/flo-processing",
    label: "Flo Processing",
    description: "Ashley's processor cockpit",
    icon: ClipboardList,
    gate: { roles: ["processor"] },
  },
  {
    section: "mortgage",
    href: "/flo",
    label: "FLO Assistant",
    description: "Ashley's real processing AI — conditions, docs, CTC",
    icon: Bot,
    gate: { roles: ["processor"] },
  },
  {
    section: "mortgage",
    href: "/coordinator",
    label: "Coordinator",
    description: "Geraldine's follow-up board",
    icon: UserCheck,
    gate: { roles: ["coordinator"] },
  },
  {
    section: "mortgage",
    href: "/my-loans",
    label: "My Loans",
    description: "Your assigned loan files",
    icon: Briefcase,
    gate: { roles: ["loan_officer"] },
  },
  {
    section: "studios",
    href: "/social",
    label: "Social Studio",
    description: "Multi-channel drafts",
    icon: Share2,
  },
  {
    section: "studios",
    href: "/marketing-assistant",
    label: "Marketing Assistant",
    description: "Real marketing AI — social, email, GBP, YouTube, compliance",
    icon: Sparkles,
    gate: { roles: ["marketing", "loan_officer"] },
  },
  {
    section: "studios",
    href: "/images",
    label: "Image Studio",
    description: "Fal.ai generation",
    icon: ImageIcon,
  },
  {
    section: "studios",
    href: "/email",
    label: "Email Studio",
    description: "Newsletters and campaigns",
    icon: Mail,
  },
  {
    section: "studios",
    href: "/calendar",
    label: "Calendar",
    description: "Content planning",
    icon: Calendar,
  },
  {
    section: "team",
    href: "/training",
    label: "Training",
    description: "Team training and tutorials",
    icon: GraduationCap,
  },
  {
    section: "team",
    href: "/training/academy",
    label: "Legends Academy",
    description: "Sales · Marketing · AI · Mastery tracks",
    icon: GraduationCap,
  },
  {
    section: "team",
    href: "/training/ai-advantage",
    label: "AI Advantage",
    description: "Jeremy's AI training video library for loan officers",
    icon: PlayCircle,
  },
  {
    section: "team",
    href: "/coaching",
    label: "Coaching",
    description: "LO Mastery & Alliance programs and 12-week curriculum",
    icon: Trophy,
  },
  {
    section: "team",
    href: "/marketing-materials",
    label: "Marketing Materials",
    description: "Templates and campaign assets",
    icon: FileStack,
  },
  {
    section: "team",
    href: "/lf-resources",
    label: "LF Resources",
    description: "Loan Factory links and guides",
    icon: Factory,
  },
  {
    section: "team",
    href: "/shared",
    label: "Shared Resources",
    description: "Owner-curated assets",
    icon: Sparkles,
  },
  {
    section: "team",
    href: "/vibe-coding",
    label: "Vibe Coding",
    description: "Build pages & posts safely with AI",
    icon: Sparkles,
  },
  {
    section: "team",
    href: "/automation",
    label: "Automations",
    description: "Allowed automations and run history",
    icon: Workflow,
  },
  {
    section: "owner",
    href: "/builder",
    label: "Builder",
    description: "Jeremy's personal build cockpit — projects, capture, plans, QA",
    icon: Wrench,
    gate: { ownerOnly: true },
  },
  {
    section: "owner",
    href: "/email-intake",
    label: "Email Intake",
    description: "Gmail AI intake — review queue, attachments, routing (Phase 1)",
    icon: Inbox,
    gate: { adminOrOwner: true },
  },
  {
    section: "owner",
    href: "/admin/setup",
    label: "Team Setup",
    description: "Roster provisioning, invites, integration status",
    icon: UserPlus,
    gate: { ownerOnly: true },
  },
  {
    section: "owner",
    href: "/admin/connections",
    label: "Connection Center",
    description: "Owner/admin integration status, destination gating, and reconnect actions",
    icon: Plug,
    gate: { adminOrOwner: true },
  },
  {
    section: "owner",
    href: "/admin/security",
    label: "Security",
    description: "Borrower data protections, RLS, OAuth, webhooks, audit coverage",
    icon: ShieldAlert,
    gate: { ownerOnly: true },
  },
  {
    section: "owner",
    href: "/admin",
    label: "Admin Center",
    description: "Users, usage, audit logs",
    icon: ShieldCheck,
    gate: { ownerOnly: true },
  },
  {
    section: "owner",
    href: "/admin/usage",
    label: "Usage & Activity",
    description: "Team-wide rollups",
    icon: ChartLine,
    gate: { ownerOnly: true },
  },
  {
    section: "owner",
    href: "/admin/users",
    label: "Users & Roles",
    description: "Manage team access",
    icon: Users,
    gate: { ownerOnly: true },
  },
  {
    section: "owner",
    href: "/admin/assets",
    label: "Asset Library",
    description: "Local logos, backgrounds, team photos",
    icon: ImageIcon,
    gate: { ownerOnly: true },
  },
  {
    section: "team",
    href: "/settings/assistant-memory",
    label: "Assistant Memory",
    description: "What your agents remember about you (private)",
    icon: Brain,
  },
  {
    section: "team",
    href: "/settings/skills",
    label: "My Skills",
    description: "Your reusable agent workflows",
    icon: Puzzle,
  },
  {
    section: "team",
    href: "/settings",
    label: "Settings",
    description: "Profile and integrations",
    icon: Settings,
  },
  {
    section: "owner",
    href: "/admin/assistant-memory",
    label: "Agent Memory (Admin)",
    description: "Audit agent memory across the team",
    icon: Brain,
    gate: { ownerOnly: true },
  },
  {
    section: "owner",
    href: "/admin/skills",
    label: "Agent Skills (Admin)",
    description: "Review, promote, and deactivate agent skills",
    icon: Puzzle,
    gate: { ownerOnly: true },
  },
];

export const NAV_SECTIONS: { key: NavItem["section"]; label: string }[] = [
  { key: "core", label: "Core" },
  { key: "mortgage", label: "Mortgage" },
  { key: "studios", label: "Studios" },
  { key: "team", label: "Team" },
  { key: "owner", label: "Owner only" },
];

export { Bell };
