"use client";

import { Bot, Sparkles, Workflow, Zap, BookOpen } from "lucide-react";
import type { LucideIcon } from "lucide-react";

import { cn } from "@/lib/utils";
import type { AtlasRouter } from "@/lib/atlas/types";

interface RouterChipProps {
  router: AtlasRouter | null | undefined;
  /** When true, the chip renders as a tiny inline pill (next to a timestamp). */
  compact?: boolean;
}

interface RouterConfig {
  label: string;
  icon: LucideIcon;
  /** Border + bg + text tone classes for the chip face. */
  tone: string;
  hint: string;
}

const ROUTER_CONFIG: Record<AtlasRouter, RouterConfig> = {
  provider: {
    label: "via AI",
    icon: Bot,
    tone: "border-indigo-400/30 bg-indigo-400/10 text-indigo-300",
    hint: "Generated by the AI provider chain",
  },
  tool: {
    label: "via tool",
    icon: Sparkles,
    tone: "border-accent-gold/40 bg-accent-gold/10 text-accent-gold",
    hint: "Atlas tool router fired this response",
  },
  n8n: {
    label: "via n8n",
    icon: Workflow,
    tone: "border-emerald-400/30 bg-emerald-400/10 text-emerald-300",
    hint: "Executed via n8n workflow bridge",
  },
  zapier: {
    label: "via Zapier",
    icon: Zap,
    tone: "border-amber-400/30 bg-amber-400/10 text-amber-300",
    hint: "Routed through Zapier MCP",
  },
  knowledge: {
    label: "via knowledge",
    icon: BookOpen,
    tone: "border-accent-gold/40 bg-accent-gold/10 text-accent-gold",
    hint: "Grounded purely in knowledge retrieval",
  },
};

export function RouterChip({ router, compact = false }: RouterChipProps) {
  if (!router) return null;
  const config = ROUTER_CONFIG[router as AtlasRouter];
  if (!config) return null;
  const Icon = config.icon;
  return (
    <span
      title={config.hint}
      className={cn(
        "inline-flex items-center gap-1 rounded-full border backdrop-blur-sm",
        config.tone,
        compact
          ? "px-1.5 py-[1px] text-[9px] font-medium uppercase tracking-[0.14em]"
          : "px-2 py-0.5 text-[10px] font-medium uppercase tracking-[0.18em]"
      )}
    >
      <Icon size={compact ? 9 : 10} />
      {config.label}
    </span>
  );
}
